export interface AirportEntry {
  iata: string;
  name: string;
  city: string;
  country: string;
}

export const AIRPORTS: AirportEntry[] = [
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "US" },
  { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "US" },
  { iata: "ORD", name: "O'Hare International", city: "Chicago", country: "US" },
  { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "US" },
  { iata: "DEN", name: "Denver International", city: "Denver", country: "US" },
  { iata: "JFK", name: "John F. Kennedy International", city: "New York", country: "US" },
  { iata: "SFO", name: "San Francisco International", city: "San Francisco", country: "US" },
  { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "US" },
  { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "US" },
  { iata: "MCO", name: "Orlando International", city: "Orlando", country: "US" },
  { iata: "EWR", name: "Newark Liberty International", city: "Newark", country: "US" },
  { iata: "MIA", name: "Miami International", city: "Miami", country: "US" },
  { iata: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", country: "US" },
  { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "US" },
  { iata: "BOS", name: "Logan International", city: "Boston", country: "US" },
  { iata: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", country: "US" },
  { iata: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "US" },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", country: "US" },
  { iata: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "US" },
  { iata: "LGA", name: "LaGuardia Airport", city: "New York", country: "US" },
  { iata: "BWI", name: "Baltimore/Washington International", city: "Baltimore", country: "US" },
  { iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington DC", country: "US" },
  { iata: "IAD", name: "Washington Dulles International", city: "Washington DC", country: "US" },
  { iata: "MDW", name: "Chicago Midway International", city: "Chicago", country: "US" },
  { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "US" },
  { iata: "SAN", name: "San Diego International", city: "San Diego", country: "US" },
  { iata: "TPA", name: "Tampa International", city: "Tampa", country: "US" },
  { iata: "PDX", name: "Portland International", city: "Portland", country: "US" },
  { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "US" },
  { iata: "STL", name: "St. Louis Lambert International", city: "St. Louis", country: "US" },
  { iata: "BNA", name: "Nashville International", city: "Nashville", country: "US" },
  { iata: "AUS", name: "Austin-Bergstrom International", city: "Austin", country: "US" },
  { iata: "MCI", name: "Kansas City International", city: "Kansas City", country: "US" },
  { iata: "RDU", name: "Raleigh-Durham International", city: "Raleigh", country: "US" },
  { iata: "SJC", name: "Norman Y. Mineta San Jose International", city: "San Jose", country: "US" },
  { iata: "OAK", name: "Oakland Metropolitan International", city: "Oakland", country: "US" },
  { iata: "SMF", name: "Sacramento International", city: "Sacramento", country: "US" },
  { iata: "SNA", name: "John Wayne Airport", city: "Orange County", country: "US" },
  { iata: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee", country: "US" },
  { iata: "CLT", name: "Charlotte Douglas International", city: "Charlotte", country: "US" },
  { iata: "PIT", name: "Pittsburgh International", city: "Pittsburgh", country: "US" },
  { iata: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", country: "US" },
  { iata: "IND", name: "Indianapolis International", city: "Indianapolis", country: "US" },
  { iata: "CMH", name: "John Glenn Columbus International", city: "Columbus", country: "US" },
  { iata: "SAT", name: "San Antonio International", city: "San Antonio", country: "US" },
  { iata: "DAL", name: "Dallas Love Field", city: "Dallas", country: "US" },
  { iata: "HOU", name: "William P. Hobby Airport", city: "Houston", country: "US" },
  { iata: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", country: "US" },
  { iata: "BUR", name: "Hollywood Burbank Airport", city: "Burbank", country: "US" },
  { iata: "OMA", name: "Eppley Airfield", city: "Omaha", country: "US" },
  { iata: "MEM", name: "Memphis International", city: "Memphis", country: "US" },
  { iata: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", country: "US" },
  { iata: "PBI", name: "Palm Beach International", city: "West Palm Beach", country: "US" },
  { iata: "RSW", name: "Southwest Florida International", city: "Fort Myers", country: "US" },
  { iata: "JAX", name: "Jacksonville International", city: "Jacksonville", country: "US" },
  { iata: "BOI", name: "Boise Airport", city: "Boise", country: "US" },
  { iata: "TUS", name: "Tucson International", city: "Tucson", country: "US" },
  { iata: "OGG", name: "Kahului Airport", city: "Maui", country: "US" },
  { iata: "KOA", name: "Ellison Onizuka Kona International", city: "Kona", country: "US" },
  { iata: "LIH", name: "Lihue Airport", city: "Kauai", country: "US" },
  { iata: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "US" },
  { iata: "GEG", name: "Spokane International", city: "Spokane", country: "US" },
  { iata: "RNO", name: "Reno-Tahoe International", city: "Reno", country: "US" },
  { iata: "ELP", name: "El Paso International", city: "El Paso", country: "US" },
  { iata: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham", country: "US" },
  { iata: "OKC", name: "Will Rogers World Airport", city: "Oklahoma City", country: "US" },
  { iata: "TUL", name: "Tulsa International", city: "Tulsa", country: "US" },
  { iata: "LIT", name: "Bill and Hillary Clinton National", city: "Little Rock", country: "US" },
  { iata: "CHS", name: "Charleston International", city: "Charleston", country: "US" },
  { iata: "SRQ", name: "Sarasota-Bradenton International", city: "Sarasota", country: "US" },
  { iata: "PWM", name: "Portland International Jetport", city: "Portland", country: "US" },
  { iata: "BTV", name: "Burlington International", city: "Burlington", country: "US" },
  { iata: "ALB", name: "Albany International", city: "Albany", country: "US" },
  { iata: "SYR", name: "Syracuse Hancock International", city: "Syracuse", country: "US" },
  { iata: "ROC", name: "Greater Rochester International", city: "Rochester", country: "US" },
  { iata: "BUF", name: "Buffalo Niagara International", city: "Buffalo", country: "US" },
  { iata: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "CA" },
  { iata: "YVR", name: "Vancouver International", city: "Vancouver", country: "CA" },
  { iata: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "CA" },
  { iata: "YYC", name: "Calgary International", city: "Calgary", country: "CA" },
  { iata: "YEG", name: "Edmonton International", city: "Edmonton", country: "CA" },
  { iata: "YOW", name: "Ottawa MacDonald-Cartier International", city: "Ottawa", country: "CA" },
  { iata: "YHZ", name: "Halifax Stanfield International", city: "Halifax", country: "CA" },
  { iata: "LHR", name: "Heathrow Airport", city: "London", country: "GB" },
  { iata: "LGW", name: "Gatwick Airport", city: "London", country: "GB" },
  { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "GB" },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "GB" },
  { iata: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "FR" },
  { iata: "ORY", name: "Paris Orly Airport", city: "Paris", country: "FR" },
  { iata: "AMS", name: "Amsterdam Schiphol Airport", city: "Amsterdam", country: "NL" },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "DE" },
  { iata: "MUC", name: "Munich Airport", city: "Munich", country: "DE" },
  { iata: "TXL", name: "Berlin Brandenburg Airport", city: "Berlin", country: "DE" },
  { iata: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "DE" },
  { iata: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid", country: "ES" },
  { iata: "BCN", name: "Barcelona-El Prat Airport", city: "Barcelona", country: "ES" },
  { iata: "FCO", name: "Leonardo da Vinci International", city: "Rome", country: "IT" },
  { iata: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "IT" },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "CH" },
  { iata: "VIE", name: "Vienna International Airport", city: "Vienna", country: "AT" },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "BE" },
  { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "DK" },
  { iata: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "SE" },
  { iata: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", country: "NO" },
  { iata: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "FI" },
  { iata: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "PT" },
  { iata: "ATH", name: "Athens International Airport", city: "Athens", country: "GR" },
  { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "PL" },
  { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "CZ" },
  { iata: "BUD", name: "Budapest Ferenc Liszt International", city: "Budapest", country: "HU" },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "IE" },
  { iata: "DXB", name: "Dubai International Airport", city: "Dubai", country: "AE" },
  { iata: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "AE" },
  { iata: "DOH", name: "Hamad International Airport", city: "Doha", country: "QA" },
  { iata: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "SA" },
  { iata: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "SA" },
  { iata: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "KW" },
  { iata: "BAH", name: "Bahrain International Airport", city: "Manama", country: "BH" },
  { iata: "TLV", name: "Ben Gurion International Airport", city: "Tel Aviv", country: "IL" },
  { iata: "AMM", name: "Queen Alia International Airport", city: "Amman", country: "JO" },
  { iata: "NRT", name: "Narita International Airport", city: "Tokyo", country: "JP" },
  { iata: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "JP" },
  { iata: "KIX", name: "Kansai International Airport", city: "Osaka", country: "JP" },
  { iata: "ICN", name: "Incheon International Airport", city: "Seoul", country: "KR" },
  { iata: "GMP", name: "Gimpo International Airport", city: "Seoul", country: "KR" },
  { iata: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "CN" },
  { iata: "PKX", name: "Beijing Daxing International Airport", city: "Beijing", country: "CN" },
  { iata: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "CN" },
  { iata: "SHA", name: "Shanghai Hongqiao International Airport", city: "Shanghai", country: "CN" },
  { iata: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "CN" },
  { iata: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "HK" },
  { iata: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "SG" },
  { iata: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "MY" },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "TH" },
  { iata: "DMK", name: "Don Mueang International Airport", city: "Bangkok", country: "TH" },
  { iata: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta", country: "ID" },
  { iata: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "PH" },
  { iata: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "AU" },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "AU" },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "AU" },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "AU" },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "NZ" },
  { iata: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi", country: "IN" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "IN" },
  { iata: "BLR", name: "Kempegowda International Airport", city: "Bengaluru", country: "IN" },
  { iata: "MAA", name: "Chennai International Airport", city: "Chennai", country: "IN" },
  { iata: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", country: "IN" },
  { iata: "GRU", name: "São Paulo/Guarulhos International Airport", city: "São Paulo", country: "BR" },
  { iata: "GIG", name: "Rio de Janeiro/Galeão International Airport", city: "Rio de Janeiro", country: "BR" },
  { iata: "BSB", name: "Brasília International Airport", city: "Brasília", country: "BR" },
  { iata: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "AR" },
  { iata: "SCL", name: "Arturo Merino Benítez International Airport", city: "Santiago", country: "CL" },
  { iata: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "CO" },
  { iata: "LIM", name: "Jorge Chávez International Airport", city: "Lima", country: "PE" },
  { iata: "MEX", name: "Mexico City International Airport", city: "Mexico City", country: "MX" },
  { iata: "CUN", name: "Cancún International Airport", city: "Cancún", country: "MX" },
  { iata: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg", country: "ZA" },
  { iata: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "ZA" },
  { iata: "CAI", name: "Cairo International Airport", city: "Cairo", country: "EG" },
  { iata: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "KE" },
  { iata: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos", country: "NG" },
  { iata: "ADD", name: "Addis Ababa Bole International Airport", city: "Addis Ababa", country: "ET" },
  { iata: "CMN", name: "Mohammed V International Airport", city: "Casablanca", country: "MA" },
];

export function searchAirports(query: string): AirportEntry[] {
  if (!query || query.trim().length < 2) return [];
  const q = query.trim().toLowerCase();
  return AIRPORTS.filter(
    (a) =>
      a.iata.toLowerCase().includes(q) ||
      a.name.toLowerCase().includes(q) ||
      a.city.toLowerCase().includes(q) ||
      a.country.toLowerCase() === q
  ).slice(0, 8);
}
