import type { ConfigEntry } from "./configRegistry_v3";

/**
 * V3.9 runtime/security registry extension.
 *
 * Phase-2 prerequisite P is intentionally scoped to Gate 1 and the isolated
 * prepaid smoke/probe runtime. The full legacy provider-content matrix remains
 * registered, but belongs to the later Phase-6 admission gate rather than P.
 */
export const V39_RUNTIME_CONFIG_REGISTRY: ConfigEntry[] = [
  {
    key: "DATABASE_RUNTIME_URL",
    type: "env",
    value: process.env.DATABASE_RUNTIME_URL ?? null,
    defaultValue: null,
    safeDefault: null,
    required: false,
    secret: true,
    producer: "environment",
    consumer: "server/db.ts",
    phase: "all",
    gate: "Phase 0",
    failureBehavior: "SAFE FALLBACK — general app pool falls back to DATABASE_URL; dedicated V3.9 pool does not use this fallback",
    description: "Optional least-privilege runtime URL for the general application pool",
  },
  {
    key: "V39_DATABASE_RUNTIME_URL",
    type: "env",
    value: process.env.V39_DATABASE_RUNTIME_URL ?? null,
    defaultValue: null,
    safeDefault: null,
    required: true,
    secret: true,
    producer: "scripts/provision_runtime_role_v39.ts",
    consumer: "server/lib/disruption/db_v39.ts",
    phase: "all",
    gate: "Phase 0",
    failureBehavior: "BLOCKED — every V3.9 DB operation fails closed when the clean-schema runtime role URL is absent",
    description: "Dedicated least-privilege V3.9 clean-schema runtime database URL",
  },
  {
    key: "V39_DB_ROLE_EVIDENCE",
    type: "env",
    value: process.env.V39_DB_ROLE_EVIDENCE ?? null,
    defaultValue: null,
    safeDefault: null,
    required: true,
    secret: false,
    producer: "scripts/provision_runtime_role_v39.ts",
    consumer: "v39_security_verify_v39.ts; v39_record_p_pass_v39.ts",
    phase: "Phase 2 prerequisite P",
    gate: "P",
    failureBehavior: "BLOCKED — P requires live least-privilege role/grant verification",
    description: "Structured evidence for the dedicated travnr_v39_runtime role",
  },
  {
    key: "V39_WEBHOOK_SECURITY_EVIDENCE",
    type: "env",
    value: process.env.V39_WEBHOOK_SECURITY_EVIDENCE ?? null,
    defaultValue: null,
    safeDefault: null,
    required: true,
    secret: false,
    producer: "scripts/configure_webhook_evidence_v39.ts",
    consumer: "v39_security_verify_v39.ts; v39_record_p_pass_v39.ts",
    phase: "Phase 2 prerequisite P",
    gate: "P",
    failureBehavior: "BLOCKED — P requires HTTPS secret-path ingress and replay-safe evidence",
    description: "No-secret webhook security evidence for the production ingress",
  },
  {
    key: "V39_PROVIDER_BLOB_MODE",
    type: "env",
    value: process.env.V39_PROVIDER_BLOB_MODE ?? null,
    defaultValue: null,
    safeDefault: null,
    required: true,
    secret: false,
    producer: "operator",
    consumer: "replitProviderBlobStore_v39.ts; phase2PrepaidSecurity_v39.ts",
    phase: "Phase 2 prerequisite P",
    gate: "P",
    failureBehavior: "BLOCKED — must equal required; default bucket/fallback storage is forbidden",
    description: "Forces provider plaintext onto the explicitly identified dedicated Replit App Storage bucket",
  },
  {
    key: "V39_PROVIDER_BLOB_BUCKET_ID",
    type: "env",
    value: process.env.V39_PROVIDER_BLOB_BUCKET_ID ?? null,
    defaultValue: null,
    safeDefault: null,
    required: true,
    secret: false,
    producer: "operator/Replit App Storage",
    consumer: "replitProviderBlobStore_v39.ts; phase2PrepaidSecurity_v39.ts",
    phase: "Phase 2 prerequisite P",
    gate: "P",
    failureBehavior: "BLOCKED — no implicit/default bucket may be used",
    description: "Explicit dedicated bucket id for independently deletable provider plaintext",
  },
  {
    key: "V39_PREPAID_RAW_RETENTION_HOURS",
    type: "env",
    value: Number(process.env.V39_PREPAID_RAW_RETENTION_HOURS ?? 168),
    defaultValue: 168,
    safeDefault: 168,
    required: false,
    secret: false,
    producer: "Phase-2 retention-scope evidence",
    consumer: "prepaidProbeRuntime_v39.ts; v39_phase2_retention_v39.ts",
    phase: "Phase 2 prerequisite P",
    gate: "P",
    failureBehavior: "BLOCKED if outside 1..168h or above the verified account-plan limit",
    description: "Maximum App-Storage raw-provider lifetime for the isolated prepaid runtime",
  },
  {
    key: "V39_PHASE2_RETENTION_APPLY_ARMED",
    type: "env",
    value: process.env.V39_PHASE2_RETENTION_APPLY_ARMED ?? "0",
    defaultValue: "0",
    safeDefault: "0",
    required: true,
    secret: false,
    producer: "operator",
    consumer: "v39_phase2_retention_v39.ts",
    phase: "Phase 2 prerequisite P",
    gate: "P",
    failureBehavior: "SAFE — destructive isolated-runtime expiry APPLY is refused unless exactly 1",
    description: "Explicit arming flag for Phase-2 prepaid session/blob expiry",
  },
  {
    key: "V39_PHASE2_RETENTION_SCOPE_EVIDENCE",
    type: "env",
    value: process.env.V39_PHASE2_RETENTION_SCOPE_EVIDENCE ?? null,
    defaultValue: null,
    safeDefault: null,
    required: true,
    secret: false,
    producer: "owner-reviewed provider-plan/storage evidence",
    consumer: "v39_security_verify_v39.ts; v39_record_p_pass_v39.ts; v39_phase2_retention_v39.ts",
    phase: "Phase 2 prerequisite P",
    gate: "P",
    failureBehavior: "BLOCKED — exact raw/FIDS limits and isolated storage topology must be owner-approved",
    description: "Machine-readable evidence for the exact Gate-1 + isolated prepaid retention scope",
  },
  {
    key: "V39_RETENTION_DEPLOYMENT_EVIDENCE",
    type: "env",
    value: process.env.V39_RETENTION_DEPLOYMENT_EVIDENCE ?? null,
    defaultValue: null,
    safeDefault: null,
    required: true,
    secret: false,
    producer: "prerequisite-P storage/recovery verification",
    consumer: "v39_security_verify_v39.ts; v39_record_p_pass_v39.ts",
    phase: "Phase 2 prerequisite P",
    gate: "P",
    failureBehavior: "BLOCKED — P cannot pass without complete recovery-topology evidence",
    description: "Structured primary/replica/backup/object/log recoverability evidence used to prove ordinary PITR cannot recover prepaid provider plaintext",
  },
  {
    key: "V39_RAW_PROVIDER_RETENTION_HOURS",
    type: "env",
    value: Number(process.env.V39_RAW_PROVIDER_RETENTION_HOURS ?? 168),
    defaultValue: 168,
    safeDefault: 168,
    required: false,
    secret: false,
    producer: "full later-phase retention policy",
    consumer: "retentionExpiry_v39.ts",
    phase: "Phase 6 retention closure",
    gate: "Phase 6",
    failureBehavior: "BLOCKED for full Phase-6 admission if outside verified limits",
    description: "Legacy/full-table raw-provider expiry clock; not a prerequisite-P substitute",
  },
  {
    key: "V39_FIDS_RETENTION_HOURS",
    type: "env",
    value: Number(process.env.V39_FIDS_RETENTION_HOURS ?? 24),
    defaultValue: 24,
    safeDefault: 24,
    required: false,
    secret: false,
    producer: "full later-phase retention policy",
    consumer: "retentionExpiry_v39.ts",
    phase: "Phase 6 retention closure",
    gate: "Phase 6",
    failureBehavior: "BLOCKED for full Phase-6 admission if outside verified limits",
    description: "Legacy/full-table FIDS expiry clock",
  },
  {
    key: "V39_RETENTION_APPLY_ARMED",
    type: "env",
    value: process.env.V39_RETENTION_APPLY_ARMED ?? "0",
    defaultValue: "0",
    safeDefault: "0",
    required: true,
    secret: false,
    producer: "operator",
    consumer: "retentionExpiry_v39.ts",
    phase: "Phase 6 retention closure",
    gate: "Phase 6",
    failureBehavior: "SAFE — full-table destructive expiry APPLY is refused unless exactly 1",
    description: "Explicit arming flag for the broader later-phase retention operator",
  },
  {
    key: "V39_RETENTION_MATRIX_EVIDENCE",
    type: "env",
    value: process.env.V39_RETENTION_MATRIX_EVIDENCE ?? null,
    defaultValue: null,
    safeDefault: null,
    required: true,
    secret: false,
    producer: "full provider terms/content review",
    consumer: "retentionExpiry_v39.ts; Phase-6 admission",
    phase: "Phase 6 retention closure",
    gate: "Phase 6",
    failureBehavior: "BLOCKED — Phase 6 cannot pass with unverified provider-content classes",
    description: "Full per-content-class legal/retention overlay; deliberately not prerequisite-P",
  },
];

export function getV39RuntimeRequiredConfigs(): ConfigEntry[] {
  return V39_RUNTIME_CONFIG_REGISTRY.filter((entry) => entry.required);
}

export function getV39RuntimeSecretConfigs(): ConfigEntry[] {
  return V39_RUNTIME_CONFIG_REGISTRY.filter((entry) => entry.secret);
}
