/** Phase-0 DB verification. Read-only except rolled-back proof transaction; never runs migrations. */
import pg from "pg";
interface Check{name:string;pass:boolean;detail:string}const checks:Check[]=[];const record=(name:string,pass:boolean,detail:string)=>{checks.push({name,pass,detail});console.log(`  [${pass?"PASS":"FAIL"}] ${name} — ${detail}`)};
async function main(){const url=process.env.DATABASE_URL;if(!url){console.error("DATABASE_URL not set — refusing to run.");process.exit(2)}const pool=new pg.Pool({connectionString:url,connectionTimeoutMillis:15000});try{
 const v=await pool.query("SELECT version()");record("connectivity",true,v.rows[0].version.split(" ").slice(0,2).join(" "));
 const t=await pool.query("SELECT schemaname || '.' || tablename AS fqn FROM pg_tables WHERE schemaname IN ('clean','public') ORDER BY 1");const names=new Set<string>(t.rows.map((r:any)=>r.fqn));record("table-inventory",true,`${names.size} tables`);
 for(const tbl of ["clean.raw_delivery","clean.raw_delivery_item","clean.processing_attempt","clean.flight_population","clean.flight_events","clean.flight_data_pre_post","clean.flight_snapshots","clean.flight_airborne_snapshots","clean.flight_outcomes","clean.historical_feature_store","clean.adb_ingest_events","clean.adb_collection_batches","clean.airborne_quarantine","clean.airborne_eligibility_evidence","clean.adb_incident_stop"])record(`table:${tbl}`,names.has(tbl),names.has(tbl)?"present":"MISSING");
 const cols=await pool.query("SELECT table_schema || '.' || table_name AS t,column_name FROM information_schema.columns WHERE table_schema='clean'");const c=new Set(cols.rows.map((r:any)=>`${r.t}:${r.column_name}`));
 for(const need of ["clean.raw_delivery:delivery_id","clean.raw_delivery:raw_body_sha256","clean.raw_delivery:received_at_utc","clean.raw_delivery_item:delivery_id","clean.raw_delivery_item:item_index","clean.processing_attempt:delivery_id","clean.flight_trajectory:flight_instance_id","clean.flight_airborne_snapshots:flight_instance_id","clean.flight_airborne_snapshots:prediction_cutoff_utc","clean.flight_airborne_snapshots:trajectory_prefix_hash","clean.airborne_eligibility_evidence:population_query_id","clean.airborne_eligibility_evidence:evidence_available_at","clean.adb_anchor_probe:confirmed_unique_lower","clean.adb_anchor_probe:confirmed_plus_ambiguous_upper","clean.adb_anchor_probe:preprobe_artifact_sha256","clean.adb_anchor_probe:probe_budget_day_id"])record(`column:${need}`,c.has(need),c.has(need)?"present":"MISSING");
 const idx=await pool.query("SELECT schemaname||'.'||tablename AS t,indexname,indexdef FROM pg_indexes WHERE schemaname='clean'");const it=idx.rows.map((r:any)=>`${r.indexname}:${r.indexdef}`).join(" | ");
 record("unique:trajectory-canonical",/uq_flight_trajectory_canonical.*flight_instance_id/i.test(it),"canonical partial unique index");record("unique:airborne-snapshot-canonical",/uq_airborne_snapshot_canonical_observation.*flight_instance_id.*event_timestamp/i.test(it),"canonical observation unique index");
 const old=await pool.query("SELECT conname FROM pg_constraint WHERE conname IN ('flight_trajectory_key','airborne_snapshot_key')");record("legacy-airborne-unique-removed",old.rowCount===0,old.rowCount===0?"removed":"legacy constraints still active");
 const client=await pool.connect();try{await client.query("BEGIN");const id=`verify_${Date.now()}`;await client.query("INSERT INTO clean.raw_delivery (delivery_id,subscription_id,http_method,raw_body,raw_body_sha256,processing_outcome,notification_items) VALUES ($1,'verify','POST','{}'::jsonb,'verify','pending',0) ON CONFLICT (delivery_id) DO NOTHING",[id]);await client.query("INSERT INTO clean.raw_delivery_item (delivery_id,item_index,raw_item,raw_item_sha256,parsing_outcome) VALUES ($1,0,'{}'::jsonb,'verify','pending') ON CONFLICT (delivery_id,item_index) DO NOTHING",[id]);await client.query("INSERT INTO clean.processing_attempt (delivery_id,attempt_index,parser_version,outcome,items_received,items_parsed,items_stored,items_skipped,items_failed,research_events_appended,ingest_event_written) VALUES ($1,0,'verify','success',1,1,1,0,0,false,false)",[id]);const [a,b,d]=await Promise.all([client.query("SELECT 1 FROM clean.raw_delivery WHERE delivery_id=$1",[id]),client.query("SELECT 1 FROM clean.raw_delivery_item WHERE delivery_id=$1",[id]),client.query("SELECT 1 FROM clean.processing_attempt WHERE delivery_id=$1",[id])]);record("raw-before-2xx-ordering",a.rowCount===1&&b.rowCount===1&&d.rowCount===1,"delivery→item→attempt readable before rollback");await client.query("ROLLBACK");record("rollback-no-junk-rows",true,"rolled back")}catch(e:any){try{await client.query("ROLLBACK")}catch{}record("raw-before-2xx-ordering",false,e?.message??String(e))}finally{client.release()}
 }finally{await pool.end()}const fail=checks.filter(x=>!x.pass);console.log(`\nRESULT: ${checks.length-fail.length}/${checks.length} checks PASS`);if(fail.length){for(const x of fail)console.log(`  - ${x.name}: ${x.detail}`);process.exit(1)}console.log("ALL DB CHECKS PASS for current Phase-0 schema.");}
main().catch((e:any)=>{console.error("db_verify_phase0_v39 failed:",e?.message??e);process.exit(1)});
