import Anthropic from "@anthropic-ai/sdk";

// Compact, cached one-line summary of a completed Bland concierge call,
// generated by Claude. Stored on bland_calls.variables.aiSummary so the
// admin "Recent Calls" list can render it without re-calling the model
// on every page load.
export type CallSummaryStructured = {
  route: string | null;
  dates: string | null;
  pax: number | null;
  cabin: string | null;
  budget: string | null;
  preferences: string | null;
};

export type CallSummary = {
  oneLiner: string;
  structured: CallSummaryStructured;
  confidence: number;
  generatedAt: string;
  model: string;
};

const ANTHROPIC_MODEL = "claude-sonnet-4-5";
const MAX_TRANSCRIPT_CHARS = 20_000;
const MAX_ONELINER_CHARS = 220;

const SYSTEM_PROMPT =
  "You are a concise note-taker for Travnr admins. You read a concierge call transcript plus any structured analysis we already extracted, and produce a single short triage line and a small structured JSON. Respond ONLY with valid JSON, no markdown, no commentary.";

let cachedClient: Anthropic | null = null;
function getClient(): Anthropic | null {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  if (!cachedClient) cachedClient = new Anthropic({ apiKey: key });
  return cachedClient;
}

export function isCallSummaryAvailable(): boolean {
  return !!process.env.ANTHROPIC_API_KEY;
}

function buildUserPrompt(transcript: string, summary: string | null, analysis: unknown): string {
  const t =
    transcript.length > MAX_TRANSCRIPT_CHARS
      ? transcript.slice(0, MAX_TRANSCRIPT_CHARS) + "\n…[truncated]…"
      : transcript;
  return [
    "CALL TRANSCRIPT:",
    "----------------",
    t || "(no transcript)",
    "",
    "BLAND-PROVIDED SUMMARY (may be empty):",
    summary || "(none)",
    "",
    "STRUCTURED ANALYSIS WE ALREADY EXTRACTED (may be partial / null fields):",
    JSON.stringify(analysis ?? {}, null, 2),
    "",
    "Produce a single one-line triage summary an admin can scan in under 2 seconds. Aim for the shape:",
    '"<pax> traveler(s), <ORIGIN>→<DEST>, <dates>, <cabin>, budget <budget>, <key preference if any>"',
    "Use the structured analysis as the source of truth; fall back to the transcript only when fields are missing. Use 3-letter airport codes when known. If a field is unknown, omit it (do not write 'unknown' or 'N/A'). Keep the line under " + MAX_ONELINER_CHARS + " characters.",
    "",
    "Also fill the structured object. Each field is a short human-readable string (not JSON), or null if unknown.",
    "",
    "Respond with this exact JSON shape and nothing else:",
    "{",
    '  "one_liner": "Family of 4, JFK→LIS, Jun 12-22, premium econ, budget $8k, prefers nonstop",',
    '  "structured": {',
    '    "route": "JFK→LIS",',
    '    "dates": "Jun 12-22",',
    '    "pax": 4,',
    '    "cabin": "premium economy",',
    '    "budget": "$8,000",',
    '    "preferences": "prefers nonstop"',
    "  },",
    '  "confidence": 0.85',
    "}",
  ].join("\n");
}

function parseClaudeJson(raw: string): CallSummary | null {
  if (!raw) return null;
  let text = raw.trim();
  if (text.startsWith("```")) {
    text = text.replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();
  }
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) return null;
  let parsed: any;
  try {
    parsed = JSON.parse(text.slice(start, end + 1));
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== "object") return null;
  const oneLinerRaw = typeof parsed.one_liner === "string" ? parsed.one_liner.trim() : "";
  if (!oneLinerRaw) return null;
  const oneLiner =
    oneLinerRaw.length > MAX_ONELINER_CHARS
      ? oneLinerRaw.slice(0, MAX_ONELINER_CHARS - 1) + "…"
      : oneLinerRaw;
  const s = parsed.structured ?? {};
  const asStr = (v: unknown): string | null => {
    if (v === null || v === undefined) return null;
    if (typeof v === "string") {
      const t = v.trim();
      return t ? t : null;
    }
    if (typeof v === "number" && Number.isFinite(v)) return String(v);
    return null;
  };
  const pax =
    typeof s.pax === "number" && Number.isFinite(s.pax) && s.pax >= 0
      ? Math.floor(s.pax)
      : null;
  const confidence =
    typeof parsed.confidence === "number" && Number.isFinite(parsed.confidence)
      ? Math.max(0, Math.min(1, parsed.confidence))
      : 0;
  return {
    oneLiner,
    structured: {
      route: asStr(s.route),
      dates: asStr(s.dates),
      pax,
      cabin: asStr(s.cabin),
      budget: asStr(s.budget),
      preferences: asStr(s.preferences),
    },
    confidence,
    generatedAt: new Date().toISOString(),
    model: ANTHROPIC_MODEL,
  };
}

// Best-effort: returns null when Claude is not configured, the transcript
// is empty, the API call throws, or the response can't be parsed. Callers
// should treat null as "fall back to whatever extracted fields you already
// have" — never propagate the failure to the user.
export async function summarizeCall(args: {
  transcript: string | null | undefined;
  summary?: string | null;
  analysis?: unknown;
  blandCallId?: string | null;
}): Promise<CallSummary | null> {
  const client = getClient();
  if (!client) return null;
  const transcript = (args.transcript || "").trim();
  if (!transcript) return null;
  const tag = args.blandCallId ? `bland_call=${args.blandCallId}` : "bland_call=?";
  try {
    const resp = await client.messages.create({
      model: ANTHROPIC_MODEL,
      max_tokens: 512,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: buildUserPrompt(transcript, args.summary ?? null, args.analysis ?? null) }],
    });
    const block = (resp.content || []).find((b: any) => b.type === "text") as
      | { type: "text"; text: string }
      | undefined;
    const result = parseClaudeJson(block?.text ?? "");
    if (!result) {
      console.warn(`[call-summary] ${tag} failed to parse Claude response`);
      return null;
    }
    console.log(
      `[call-summary] ${tag} generated confidence=${result.confidence.toFixed(2)} chars=${result.oneLiner.length}`,
    );
    return result;
  } catch (err: any) {
    console.warn(`[call-summary] ${tag} Anthropic error:`, err?.message || err);
    return null;
  }
}

// Type-guard / narrower for what we may have stored on
// bland_calls.variables.aiSummary in the past. Returns the summary if it
// looks well-shaped, else null. Defensive because `variables` is a freeform
// jsonb column shared with Bland-provided fields.
export function pickStoredSummary(variables: unknown): CallSummary | null {
  if (!variables || typeof variables !== "object") return null;
  const v = variables as { aiSummary?: unknown };
  const s = v.aiSummary;
  if (!s || typeof s !== "object") return null;
  const candidate = s as Partial<CallSummary> & { structured?: Partial<CallSummaryStructured> };
  if (typeof candidate.oneLiner !== "string" || !candidate.oneLiner.trim()) return null;
  const structured: Partial<CallSummaryStructured> = candidate.structured ?? {};
  return {
    oneLiner: candidate.oneLiner,
    structured: {
      route: typeof structured.route === "string" ? structured.route : null,
      dates: typeof structured.dates === "string" ? structured.dates : null,
      pax: typeof structured.pax === "number" ? structured.pax : null,
      cabin: typeof structured.cabin === "string" ? structured.cabin : null,
      budget: typeof structured.budget === "string" ? structured.budget : null,
      preferences: typeof structured.preferences === "string" ? structured.preferences : null,
    },
    confidence: typeof candidate.confidence === "number" ? candidate.confidence : 0,
    generatedAt: typeof candidate.generatedAt === "string" ? candidate.generatedAt : "",
    model: typeof candidate.model === "string" ? candidate.model : "",
  };
}

// Merge a freshly-generated CallSummary into an existing variables jsonb,
// preserving every other key (especially Bland's __analysis, dynamic-data
// response_data context, etc.). Returns the new object — callers persist
// it via storage.updateBlandCall(id, { variables: merged }).
export function mergeSummaryIntoVariables(
  variables: unknown,
  summary: CallSummary,
): Record<string, unknown> {
  const base =
    variables && typeof variables === "object" && !Array.isArray(variables)
      ? { ...(variables as Record<string, unknown>) }
      : {};
  base.aiSummary = summary;
  return base;
}
